# Generated by Django 4.2.4 on 2023-08-11 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20669acc-fd41-46a4-b39d-afe98e83970e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20669acc-fd41-46a4-b39d-afe98e83970e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
