# Generated by Django 4.2.4 on 2023-08-12 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ccff0642-2ef6-46c3-8715-f109bba63af0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ccff0642-2ef6-46c3-8715-f109bba63af0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
