# Generated by Django 4.2.4 on 2023-08-12 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('274bd58d-552e-4a17-b793-9e8f5cb9bff9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('274bd58d-552e-4a17-b793-9e8f5cb9bff9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
