# Generated by Django 4.2.4 on 2023-08-12 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81bc2248-e6da-429f-a2e4-8edbd952f713'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81bc2248-e6da-429f-a2e4-8edbd952f713'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
