# Generated by Django 4.2.4 on 2023-08-12 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('820eaeb2-1623-4f04-9ab0-e811a7994e5c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('820eaeb2-1623-4f04-9ab0-e811a7994e5c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
