# Generated by Django 4.2.4 on 2023-08-16 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d596e8b-5552-445b-9806-0e1c024ff14a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d596e8b-5552-445b-9806-0e1c024ff14a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
